spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.mongo.MongoAutoConfiguration
  mail:
    host: smtp.gmail.com
    port: 587
    username: lenus.team@gmail.com
    password: password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

mongodb:
  central:
    uri: "mongodb+srv://m001-student:azerty123@testcluster.yhrmt.mongodb.net/myDatabase?retryWrites=true&w=majority"
  local:
    uri: "mongodb+srv://fares:test@cluster0.csscd.gcp.mongodb.net/LocalDB?retryWrites=true&w=majority"

lenus:
  app:
    jwtSecret : securityKey
    jwtExpirationMs : 86400000

